# Generated by Django 5.2.7 on 2025-10-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['name'], name='idx_country_name'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['region'], name='idx_country_region'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['currency_code'], name='idx_country_currency'),
        ),
    ]
